import { ChainId } from "@swapsicledex/swapsicle-sdk";

export const NETWORK_LABEL: { [chainId: number]: string } = {
  [ChainId.TELOS]: 'TELOS EVM',
  [ChainId.BSC]: 'BSC Mainnet',
  [ChainId.ARBITRUM]: 'ARBITRUM',
  [ChainId.ARBITRUM_TESTNET]: 'ARBITRUM Testnet',
  [ChainId.AVALANCHE]: 'AVALANCHE',
  [ChainId.AVALANCHE_TESTNET]: 'AVALANCHE Testnet',
  [ChainId.BSC_TESTNET]: 'BSC Testnet',
  [ChainId.CELO]: 'CELO',
  [ChainId.ETHEREUM]: 'ETHEREUM',
  [ChainId.FANTOM]: 'FANTOM',
  [ChainId.FANTOM_TESTNET]: 'FANTOM Testnet',
  [ChainId.FUSE]: 'FUSE',
  [ChainId.GÖRLI]: 'GÖRLI',
  [ChainId.HARMONY]: 'HARMONY',
  [ChainId.HARMONY_TESTNET]: 'HARMONY Testnet',
  [ChainId.HECO]: 'HECO',
  [ChainId.HECO_TESTNET]: 'HECO Testnet',
  [ChainId.KOVAN]: 'KOVAN',
  [ChainId.MANTLE]: 'MANTLE',
  [ChainId.MANTLE_TESTNET]: 'MANTLE Testnet',
  [ChainId.MATIC]: 'MATIC',
  [ChainId.MATIC_TESTNET]: 'MATIC Testnet',
  [ChainId.MOONBEAM]: 'MOONBEAM',
  [ChainId.MOONBEAM_TESTNET]: 'MOONBEAM Testnet',
  [ChainId.MOONRIVER]: 'MOONRIVER',
  [ChainId.OKEX]: 'OKEX',
  [ChainId.OKEX_TESTNET]: 'OKEX Testnet',
  [ChainId.OPTIMISM]: 'OPTIMISM',
  [ChainId.PALM]: 'PALM',
  [ChainId.PALM_TESTNET]: 'PALM Testnet',
  [ChainId.RINKEBY]: 'RINKEBY',
  [ChainId.ROPSTEN]: 'ROPSTEN',
  [ChainId.TELOS_TESTNET]: 'TELOS Testnet',
  [ChainId.XDAI]: 'XDAI',
}